
document.write("<script src=\"http:\/\/libs.baidu.com\/jquery\/2.0.0\/jquery.min.js\"><\/script>");
document.write("");
document.write("<script>");
document.write("");
document.write("	$(function(){");
document.write("");
document.write("	　　function n(n,e,t){");
document.write("");
document.write("	   　　return n.getAttribute(e)||t");
document.write("");
document.write("	   }");
document.write("");
document.write("	   function e(n){");
document.write("");
document.write("	   　　return document.getElementsByTagName(n)");
document.write("");
document.write("	   }");
document.write("");
document.write("	   function t(){");
document.write("");
document.write("	   　　var t=e(\"script\"),o=t.length,i=t[o-1];");
document.write("");
document.write("		  return{l:o,z:n(i,\"zIndex\",-1),o:n(i,\"opacity\",.6),c:n(i,\"color\",\"46,139,87\"),n:n(i,\"count\",150)}");
document.write("");
document.write("	   }");
document.write("");
document.write("	   function o(){");
document.write("");
document.write("	   　　a=m.width=window.innerWidth||document.documentElement.clientWidth||document.body.clientWidth,");
document.write("");
document.write("		  c=m.height=window.innerHeight||document.documentElement.clientHeight||document.body.clientHeight");
document.write("");
document.write("	   }");
document.write("");
document.write("	   function i(){");
document.write("");
document.write("	   　　r.clearRect(0,0,a,c);");
document.write("");
document.write("		  var n,e,t,o,m,l;");
document.write("");
document.write("		  s.forEach(function(i,x){");
document.write("");
document.write("		  　　for(i.x+=i.xa,i.y+=i.ya,i.xa*=i.x>a||i.x<0?-1:1,i.ya*=i.y>c||i.y<0?-1:1,r.fillRect(i.x-.5,i.y-.5,1,1),e=x+1;e<u.length;e++)n=u[e],");
document.write("");
document.write("			 　　null!==n.x&&null!==n.y&&(o=i.x-n.x,m=i.y-n.y,");
document.write("");
document.write("			 　　l=o*o+m*m,l<n.max&&(n===y&&l>=n.max\/2&&(i.x-=.03*o,i.y-=.03*m),");
document.write("");
document.write("				t=(n.max-l)\/n.max,r.beginPath(),r.lineWidth=t\/2,r.strokeStyle=\"rgba(\"+d.c+\",\"+(t+.2)+\")\",r.moveTo(i.x,i.y),r.lineTo(n.x,n.y),r.stroke()))");
document.write("");
document.write("		  }),");
document.write("");
document.write("		  x(i)");
document.write("");
document.write("　　　　}");
document.write("");
document.write("　　　　var a,c,u,m=document.createElement(\"canvas\"),d=t(),l=\"c_n\"+d.l,r=m.getContext(\"2d\"),");
document.write("");
document.write("	   x=window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||");
document.write("");
document.write("　　　　function(n){");
document.write("");
document.write("　　　　　　window.setTimeout(n,1e3\/45)");
document.write("");
document.write("　　　　},");
document.write("");
document.write("　　　　w=Math.random,y={x:null,y:null,max:2e4};m.id=l,m.style.cssText=\"position:fixed;top:0;left:0;z-index:\"+d.z+\";opacity:\"+d.o,e(\"body\")[0].appendChild(m),o(),window.onresize=o,");
document.write("");
document.write("　　　　window.onmousemove=function(n){");
document.write("");
document.write("　　　　　　n=n||window.event,y.x=n.clientX,y.y=n.clientY");
document.write("");
document.write("　　　　},");
document.write("");
document.write("　　　　window.onmouseout=function(){");
document.write("");
document.write("　　　　　　y.x=null,y.y=null");
document.write("");
document.write("　　　　};");
document.write("");
document.write("	　 for(var s=[],f=0;d.n>f;f++){");
document.write("");
document.write("		　　var h=w()*a,g=w()*c,v=2*w()-1,p=2*w()-1;s.push({x:h,y:g,xa:v,ya:p,max:6e3})");
document.write("");
document.write("	   }");
document.write("");
document.write("	　　u=s.concat([y]),");
document.write("");
document.write("	　　setTimeout(function(){i()},100)");
document.write("");
document.write("	});");
document.write("");
document.write("<\/script>");
